### ISSUE TITLE
Installing redis-config fails...

### ISSUE THREAD

**Issue by Richard87** [oroinc/redis-config#4]
Hi!

I'm trying to install Redis, but it fails misreably...

This is my process:
1. `git clone https://github.com/orocrm/crm-application.git .`
2. `curl -s https://getcomposer.org/installer | php`
3. `php composer.phar install --prefer-dist --no-dev`
4. `php app/console oro:install --force --drop-database`
5. `php composer.phar require oro/redis-config`

Wich fails with this message:

```
crm@do-2:~/crm$ php composer.phar require oro/redis-config
Using version ^1.2 for oro/redis-config
./composer.json has been updated

Installation failed, reverting ./composer.json to its original content.


  [RuntimeException]
  The lock file does not contain require-dev information, run install with the --no-dev option or run update to install those packages.


require [--dev] [--prefer-source] [--prefer-dist] [--no-plugins] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...
```

If I run `php composer.phar require oro/redis-config --no-dev` it fails with this message:

```
crm@do-2:~/crm$ php composer.phar require oro/redis-config --no-dev


  [Symfony\Component\Console\Exception\RuntimeException]
  The "--no-dev" option does not exist.


require [--dev] [--prefer-source] [--prefer-dist] [--no-plugins] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...
```

Any help would be greatly appreciated...

**Comment by RocKordier** [comment]
Hey @Richard87 
i think its more a composer than an oro issue.
It's because you run `php composer.phar install` with the `--no-dev` option. After that the lock file dose not contain a require-dev part and it seams that it's required for the `composer require` command. 

Please run the `composer require` with `--update-no-dev`, i think that should fix it. Otherwise you can run the `composer install` without `--no-dev` (if there is no composer.lock) or you can run `composer update` instead to regenerate the composer.lock file.

Hope that will help :)

**Comment by Richard87** [comment]
Hi, thanks! 

`--update-no-dev` worked, the problem is that the composer.lock file in the Git repo is missing the require-dev section :(

Also, running the Composer install require about 2.5gb of memory :/ 

Antway, it works :) Thanks!
